INSERT INTO city (
    name, state, country, culture, tourist_spots, food,
    best_time_to_visit, category, entry_fee, is_hidden_gem, language, nearby_attractions
) VALUES
('Delhi', 'Delhi', 'India',
 'Capital city with rich Mughal and modern heritage',
 'India Gate, Red Fort, Qutub Minar',
 'Chole Bhature, Butter Chicken',
 'October to March',
 'HERITAGE',
 'Free / varies by monument',
 false,
 'Hindi, English',
 'Humayun''s Tomb, Lotus Temple'),

('Mumbai', 'Maharashtra', 'India',
 'Financial capital with Bollywood and coastal charm',
 'Gateway of India, Marine Drive, Elephanta Caves',
 'Vada Pav, Pav Bhaji',
 'November to February',
 'PARTY',
 'Free / varies by attraction',
 false,
 'Marathi, Hindi, English',
 'Juhu Beach, Siddhivinayak Temple'),

('Auli', 'Uttarakhand', 'India',
 'Popular skiing destination with Himalayan views',
 'Auli Ski Resort, Gorson Bugyal, Joshimath',
 'Aloo Ke Gutke, Chainsoo',
 'December to March',
 'ADVENTURE',
 'Varies',
 false,
 'Hindi, English',
 'Joshimath, Nanda Devi National Park'),

('Mukteshwar', 'Uttarakhand', 'India',
 'Peaceful hill town with orchards and Himalayan views',
 'Mukteshwar Temple, Chauli Ki Jali, Sunrise Point',
 'Aloo Paratha, Bhatt Ki Churkani',
 'March to June, September to November',
 'MOUNTAINS',
 'Free',
 true,
 'Hindi',
 'Nainital, Almora'),

('Nainital', 'Uttarakhand', 'India',
 'Lake city surrounded by mountains and colonial charm',
 'Naini Lake, Snow View Point, Naina Devi Temple',
 'Bal Mithai, Aloo Ke Gutke',
 'March to June, September to November',
 'MOUNTAINS',
 'Free / varies',
 false,
 'Hindi, English',
 'Bhimtal, Mukteshwar'),

('Mussoorie', 'Uttarakhand', 'India',
 'Queen of Hills with scenic viewpoints and waterfalls',
 'Kempty Falls, Mall Road, Gun Hill',
 'Maggi, Momos, Garhwali Cuisine',
 'March to June, September to November',
 'MOUNTAINS',
 'Free / varies',
 false,
 'Hindi, English',
 'Dhanaulti, Dehradun'),

('Rishikesh', 'Uttarakhand', 'India',
 'Yoga capital of the world and adventure sports hub',
 'Laxman Jhula, Triveni Ghat, River Rafting',
 'Satvik Food, Aloo Puri',
 'September to April',
 'ADVENTURE',
 'Free / varies',
 false,
 'Hindi, English',
 'Haridwar, Shivpuri'),

('Haridwar', 'Uttarakhand', 'India',
 'Holy city on the banks of Ganga river',
 'Har Ki Pauri, Mansa Devi Temple',
 'Kachori, Jalebi',
 'October to March',
 'RELIGIOUS',
 'Free',
 false,
 'Hindi',
 'Rishikesh, Rajaji National Park'),

('Shimla', 'Himachal Pradesh', 'India',
 'Colonial hill station and summer capital of British India',
 'Mall Road, Kufri, Jakhoo Temple',
 'Siddu, Chana Madra',
 'March to June, December to February',
 'MOUNTAINS',
 'Free / varies',
 false,
 'Hindi, English',
 'Manali, Kufri'),

('Manali', 'Himachal Pradesh', 'India',
 'Adventure and honeymoon destination in Himalayas',
 'Solang Valley, Rohtang Pass, Hadimba Temple',
 'Trout Fish, Momos',
 'October to February',
 'ADVENTURE',
 'Free / varies',
 false,
 'Hindi, English',
 'Kasol, Leh'),

('Dharamshala', 'Himachal Pradesh', 'India',
 'Home of Dalai Lama and Tibetan culture',
 'McLeod Ganj, Triund Trek, Bhagsu Falls',
 'Momos, Thukpa',
 'March to June, September to November',
 'RELIGIOUS',
 'Free',
 true,
 'Hindi, Tibetan, English',
 'McLeod Ganj, Palampur'),

('Leh', 'Ladakh', 'India',
 'High altitude desert with monasteries and landscapes',
 'Pangong Lake, Nubra Valley, Leh Palace',
 'Thukpa, Momos',
 'May to September',
 'ADVENTURE',
 'Free / varies',
 true,
 'Hindi, Ladakhi',
 'Khardung La, Kargil'),

('Srinagar', 'Jammu and Kashmir', 'India',
 'Beautiful valley known for lakes and houseboats',
 'Dal Lake, Mughal Gardens, Shankaracharya Temple',
 'Kashmiri Wazwan, Rogan Josh',
 'April to October',
 'HERITAGE',
 'Free / varies',
 false,
 'Kashmiri, Urdu, Hindi',
 'Gulmarg, Pahalgam'),

('Gulmarg', 'Jammu and Kashmir', 'India',
 'Famous ski resort and winter wonderland',
 'Gulmarg Gondola, Apharwat Peak',
 'Kashmiri Cuisine, Kahwa',
 'December to March',
 'ADVENTURE',
 'Varies',
 true,
 'Kashmiri, Hindi',
 'Srinagar, Pahalgam'),

('Pahalgam', 'Jammu and Kashmir', 'India',
 'Valley of shepherds with scenic beauty',
 'Betaab Valley, Aru Valley, Lidder River',
 'Kashmiri Wazwan',
 'March to November',
 'MOUNTAINS',
 'Free',
 true,
 'Kashmiri',
 'Srinagar, Gulmarg'),

('Darjeeling', 'West Bengal', 'India',
 'Famous tea gardens and Himalayan railway',
 'Tiger Hill, Toy Train, Batasia Loop',
 'Momos, Thukpa, Tea',
 'March to May, September to November',
 'MOUNTAINS',
 'Free / varies',
 false,
 'Nepali, Bengali, Hindi',
 'Kalimpong, Gangtok'),

('Gangtok', 'Sikkim', 'India',
 'Capital of Sikkim with monasteries and views',
 'MG Road, Tsomgo Lake, Rumtek Monastery',
 'Momos, Thukpa',
 'March to June, September to December',
 'MOUNTAINS',
 'Free',
 false,
 'Nepali, Hindi, English',
 'Nathula Pass, Lachung'),

('Ooty', 'Tamil Nadu', 'India',
 'Queen of Nilgiris with tea plantations',
 'Ooty Lake, Botanical Garden, Doddabetta Peak',
 'South Indian Food, Chocolate',
 'March to June, September to November',
 'MOUNTAINS',
 'Free / varies',
 false,
 'Tamil, English',
 'Coonoor, Kotagiri'),

('Coorg', 'Karnataka', 'India',
 'Coffee plantations and misty hills',
 'Abbey Falls, Raja’s Seat, Coffee Estates',
 'Pandi Curry, Coffee',
 'October to March',
 'MOUNTAINS',
 'Free',
 true,
 'Kannada, English',
 'Mysore, Wayanad'),

('Mysore', 'Karnataka', 'India',
 'Royal heritage city of palaces',
 'Mysore Palace, Brindavan Gardens',
 'Mysore Pak, Dosa',
 'October to February',
 'HERITAGE',
 'Free / varies',
 false,
 'Kannada, English',
 'Coorg, Bangalore'),

('Goa', 'Goa', 'India',
 'Beach paradise with nightlife and Portuguese heritage',
 'Baga Beach, Calangute Beach, Basilica of Bom Jesus',
 'Seafood, Goan Curry, Bebinca',
 'November to February',
 'BEACHES',
 'Free / varies',
 false,
 'Konkani, English',
 'Dudhsagar Falls, Panaji'),

('Alleppey', 'Kerala', 'India',
 'Backwater destination with houseboats',
 'Alleppey Backwaters, Vembanad Lake',
 'Appam, Fish Curry',
 'October to March',
 'BEACHES',
 'Free / varies',
 true,
 'Malayalam, English',
 'Kumarakom, Kochi'),
 ('Shillong', 'Meghalaya', 'India',
 'Scotland of the East with waterfalls and hills',
 'Umiam Lake, Elephant Falls, Shillong Peak',
 'Jadoh, Momos',
 'March to June, September to November',
 'MOUNTAINS',
 'Free',
 false,
 'Khasi, English',
 'Cherrapunji, Mawlynnong'),

('Cherrapunji', 'Meghalaya', 'India',
 'One of the wettest places on Earth with living root bridges',
 'Nohkalikai Falls, Mawsmai Cave, Living Root Bridges',
 'Jadoh, Bamboo Shoot Curry',
 'June to September',
 'HIDDEN_GEM',
 'Free',
 true,
 'Khasi, English',
 'Shillong, Mawlynnong'),

('Mawlynnong', 'Meghalaya', 'India',
 'Asia’s cleanest village known for eco-tourism',
 'Living Root Bridge, Sky View Point',
 'Local Khasi Cuisine',
 'March to June',
 'HIDDEN_GEM',
 'Free',
 true,
 'Khasi, English',
 'Cherrapunji, Dawki'),

('Dawki', 'Meghalaya', 'India',
 'Crystal clear river and boating destination',
 'Umngot River, Dawki Bridge',
 'Fish Curry, Rice',
 'October to April',
 'HIDDEN_GEM',
 'Free',
 true,
 'Khasi, English',
 'Mawlynnong, Shillong'),

('Kovalam', 'Kerala', 'India',
 'Famous beach destination with lighthouse views',
 'Lighthouse Beach, Hawa Beach',
 'Seafood, Appam',
 'September to March',
 'BEACHES',
 'Free',
 false,
 'Malayalam, English',
 'Trivandrum, Varkala'),

('Varkala', 'Kerala', 'India',
 'Cliff beach with natural springs and sunsets',
 'Varkala Cliff, Papanasam Beach',
 'Seafood, Kerala Parotta',
 'October to March',
 'BEACHES',
 'Free',
 true,
 'Malayalam, English',
 'Kovalam, Trivandrum'),

('Wayanad', 'Kerala', 'India',
 'Green hills, forests and wildlife sanctuary',
 'Edakkal Caves, Banasura Sagar Dam',
 'Kerala Sadya, Bamboo Rice',
 'October to May',
 'MOUNTAINS',
 'Free / varies',
 true,
 'Malayalam, English',
 'Ooty, Coorg'),

('Kumarakom', 'Kerala', 'India',
 'Backwater village with houseboat experience',
 'Vembanad Lake, Bird Sanctuary',
 'Fish Curry, Coconut Rice',
 'November to February',
 'BEACHES',
 'Free / varies',
 true,
 'Malayalam, English',
 'Alleppey, Kochi'),

('Pondicherry', 'Puducherry', 'India',
 'French colonial town with beaches and cafes',
 'Promenade Beach, Auroville, French Quarter',
 'French Cuisine, Seafood',
 'October to March',
 'BEACHES',
 'Free',
 false,
 'Tamil, French, English',
 'Chennai, Mahabalipuram'),

('Mahabalipuram', 'Tamil Nadu', 'India',
 'UNESCO heritage coastal temple town',
 'Shore Temple, Five Rathas, Arjuna’s Penance',
 'Seafood, South Indian Meals',
 'November to February',
 'HERITAGE',
 'Free / varies',
 false,
 'Tamil, English',
 'Chennai, Pondicherry'),

('Gokarna', 'Karnataka', 'India',
 'Peaceful beach alternative to Goa',
 'Om Beach, Kudle Beach, Half Moon Beach',
 'Seafood, South Indian Food',
 'October to March',
 'BEACHES',
 'Free',
 true,
 'Kannada, English',
 'Goa, Udupi'),

('Andaman Islands', 'Andaman and Nicobar', 'India',
 'Tropical islands with crystal clear water and coral reefs',
 'Radhanagar Beach, Cellular Jail, Havelock Island',
 'Seafood',
 'October to May',
 'BEACHES',
 'Varies',
 false,
 'Hindi, English',
 'Neil Island, Port Blair'),

('Lakshadweep', 'Lakshadweep', 'India',
 'Remote coral islands with untouched beaches',
 'Agatti Island, Bangaram Island',
 'Seafood, Coconut-based dishes',
 'October to March',
 'HIDDEN_GEM',
 'Permit Required',
 true,
 'Malayalam, English',
 'Arabian Sea Islands'),

('Udaipur', 'Rajasthan', 'India',
 'City of lakes and royal palaces',
 'Lake Pichola, City Palace, Jag Mandir',
 'Dal Baati, Laal Maas',
 'September to March',
 'HERITAGE',
 'Free / varies',
 false,
 'Hindi, Rajasthani',
 'Mount Abu, Jodhpur'),

('Hampi', 'Karnataka', 'India',
 'Ancient ruins and UNESCO heritage site',
 'Virupaksha Temple, Vittala Temple, Stone Chariot',
 'South Indian Thali',
 'October to February',
 'HERITAGE',
 'Free',
 true,
 'Kannada, English',
 'Hospet, Badami'),
 ('Amritsar', 'Punjab', 'India',
 'Spiritual city known for Golden Temple and Sikh heritage',
 'Golden Temple, Jallianwala Bagh, Wagah Border',
 'Amritsari Kulcha, Lassi',
 'October to March',
 'RELIGIOUS',
 'Free',
 false,
 'Punjabi, Hindi',
 'Wagah Border Ceremony'),

('Madurai', 'Tamil Nadu', 'India',
 'Ancient temple city known as cultural capital of Tamil Nadu',
 'Meenakshi Temple, Thirumalai Nayakkar Palace',
 'Idli, Jigarthanda',
 'October to March',
 'HERITAGE',
 'Free / varies',
 false,
 'Tamil',
 'Rameswaram, Kodaikanal'),

('Rameswaram', 'Tamil Nadu', 'India',
 'Sacred island town linked to Ramayana mythology',
 'Ramanathaswamy Temple, Pamban Bridge',
 'Seafood, South Indian Meals',
 'October to April',
 'RELIGIOUS',
 'Free / varies',
 false,
 'Tamil',
 'Dhanushkodi'),

('Kodaikanal', 'Tamil Nadu', 'India',
 'Princess of Hill Stations with lakes and forests',
 'Kodaikanal Lake, Coaker’s Walk, Pillar Rocks',
 'Home-made Chocolates, South Indian Food',
 'March to June, September to October',
 'MOUNTAINS',
 'Free',
 true,
 'Tamil, English',
 'Ooty, Madurai'),

('Jodhpur', 'Rajasthan', 'India',
 'Blue city known for forts and desert culture',
 'Mehrangarh Fort, Umaid Bhawan Palace',
 'Dal Baati, Mirchi Vada',
 'October to March',
 'HERITAGE',
 'Free / varies',
 false,
 'Hindi, Rajasthani',
 'Jaisalmer, Udaipur'),

('Jaisalmer', 'Rajasthan', 'India',
 'Golden city in Thar Desert with sand dunes',
 'Jaisalmer Fort, Sam Sand Dunes, Gadisar Lake',
 'Ker Sangri, Dal Baati',
 'October to March',
 'HERITAGE',
 'Free / varies',
 true,
 'Hindi, Rajasthani',
 'Jodhpur, Bikaner'),

('Bikaner', 'Rajasthan', 'India',
 'Desert city famous for forts and sweets',
 'Junagarh Fort, Karni Mata Temple',
 'Bikaneri Bhujia, Rasgulla',
 'October to March',
 'HERITAGE',
 'Free / varies',
 false,
 'Hindi, Rajasthani',
 'Jaisalmer, Jaipur'),

('Munnar', 'Kerala', 'India',
 'Tea plantation hills and misty landscapes',
 'Tea Gardens, Eravikulam National Park',
 'Kerala Tea, Appam',
 'September to March',
 'MOUNTAINS',
 'Free / varies',
 true,
 'Malayalam, English',
 'Thekkady, Cochin'),

('Thekkady', 'Kerala', 'India',
 'Wildlife and spice plantation destination',
 'Periyar Wildlife Sanctuary, Boat Safari',
 'Spiced Kerala Food',
 'October to February',
 'ADVENTURE',
 'Free / varies',
 true,
 'Malayalam, English',
 'Munnar, Kumarakom'),

('Kanyakumari', 'Tamil Nadu', 'India',
 'Southernmost tip of India with ocean views',
 'Vivekananda Rock Memorial, Sunset Point',
 'Seafood, South Indian Meals',
 'October to March',
 'BEACHES',
 'Free / varies',
 false,
 'Tamil',
 'Rameswaram, Madurai'),

('Ajmer', 'Rajasthan', 'India',
 'Religious city famous for Ajmer Sharif Dargah',
 'Ajmer Sharif Dargah, Ana Sagar Lake',
 'Kadhi Kachori, Sweets',
 'October to March',
 'RELIGIOUS',
 'Free',
 false,
 'Hindi, Urdu',
 'Pushkar'),

('Pushkar', 'Rajasthan', 'India',
 'Holy town with sacred lake and camel fair',
 'Pushkar Lake, Brahma Temple',
 'Malpua, Kachori',
 'October to March',
 'RELIGIOUS',
 'Free',
 true,
 'Hindi, Rajasthani',
 'Ajmer'),

('Lonavala', 'Maharashtra', 'India',
 'Popular monsoon hill station near Mumbai',
 'Tiger Point, Bhushi Dam, Karla Caves',
 'Chikki, Vada Pav',
 'June to September',
 'MOUNTAINS',
 'Free',
 true,
 'Marathi, Hindi',
 'Pune, Mumbai'),

('Mahabaleshwar', 'Maharashtra', 'India',
 'Strawberry hills and scenic viewpoints',
 'Arthur’s Seat, Venna Lake, Mapro Garden',
 'Strawberries, Corn Patties',
 'October to June',
 'MOUNTAINS',
 'Free / varies',
 true,
 'Marathi, Hindi',
 'Pune, Panchgani'),

('Panchgani', 'Maharashtra', 'India',
 'Quiet hill station with valley views',
 'Table Land, Sydney Point',
 'Fresh Strawberries, Parathas',
 'September to May',
 'MOUNTAINS',
 'Free',
 true,
 'Marathi, Hindi',
 'Mahabaleshwar, Lonavala'),
 ('Kaziranga', 'Assam', 'India',
 'Wildlife sanctuary famous for one-horned rhinoceros',
 'Kaziranga National Park, Jeep Safari, Elephant Safari',
 'Assamese Thali, Pitha',
 'November to April',
 'ADVENTURE',
 'Entry Fee Applicable',
 true,
 'Assamese, Hindi, English',
 'Tezpur, Jorhat'),

('Tawang', 'Arunachal Pradesh', 'India',
 'Buddhist monastery town in Himalayas',
 'Tawang Monastery, Sela Pass, Madhuri Lake',
 'Thukpa, Momos',
 'March to October',
 'RELIGIOUS',
 'Free / varies',
 true,
 'Monpa, Hindi',
 'Bomdila, Dirang'),

('Ziro Valley', 'Arunachal Pradesh', 'India',
 'Scenic valley known for pine hills and music festival',
 'Ziro Music Festival, Talley Valley',
 'Rice Beer, Bamboo Shoot Curry',
 'March to October',
 'HIDDEN_GEM',
 'Free',
 true,
 'Apatani, English',
 'Itanagar'),

('Gangtok East', 'Sikkim', 'India',
 'Extension of Gangtok region with monasteries',
 'Enchey Monastery, Ganesh Tok',
 'Momos, Thukpa',
 'March to June',
 'MOUNTAINS',
 'Free',
 false,
 'Nepali, Hindi',
 'Gangtok, Tsomgo Lake'),

('Kalimpong', 'West Bengal', 'India',
 'Quiet hill station with orchid nurseries',
 'Deolo Hill, Durpin Monastery',
 'Momos, Thukpa',
 'March to June',
 'MOUNTAINS',
 'Free',
 true,
 'Nepali, Bengali',
 'Darjeeling, Gangtok'),

('Puri', 'Odisha', 'India',
 'Religious coastal city with Jagannath Temple',
 'Jagannath Temple, Puri Beach',
 'Khichdi, Pakhala',
 'October to February',
 'RELIGIOUS',
 'Free',
 false,
 'Odia, Hindi',
 'Konark, Bhubaneswar'),

('Konark', 'Odisha', 'India',
 'Famous for Sun Temple UNESCO heritage site',
 'Konark Sun Temple, Chandrabhaga Beach',
 'Seafood, Odia Cuisine',
 'October to March',
 'HERITAGE',
 'Free / varies',
 true,
 'Odia',
 'Puri, Bhubaneswar'),

('Bhubaneswar', 'Odisha', 'India',
 'Temple city with ancient architecture',
 'Lingaraj Temple, Udayagiri Caves',
 'Dalma, Pakhala',
 'October to March',
 'HERITAGE',
 'Free',
 false,
 'Odia',
 'Puri, Konark'),

('Shillong Peak Viewpoint', 'Meghalaya', 'India',
 'Highest point offering panoramic views of Shillong',
 'Shillong Peak, Elephant Falls',
 'Jadoh, Khasi Food',
 'March to June',
 'MOUNTAINS',
 'Free',
 true,
 'Khasi, English',
 'Shillong City'),

('Itanagar', 'Arunachal Pradesh', 'India',
 'Capital city surrounded by hills and nature',
 'Ita Fort, Ganga Lake',
 'Bamboo Shoot Curry',
 'March to October',
 'HIDDEN_GEM',
 'Free',
 false,
 'Hindi, English',
 'Ziro Valley'),

('Spiti Valley', 'Himachal Pradesh', 'India',
 'Cold desert mountain valley with monasteries',
 'Key Monastery, Chandratal Lake',
 'Thukpa, Butter Tea',
 'May to September',
 'ADVENTURE',
 'Free',
 true,
 'Hindi, Tibetan',
 'Manali, Kaza'),

('Kaza', 'Himachal Pradesh', 'India',
 'Main town of Spiti Valley',
 'Komic Village, Hikkim Post Office',
 'Local Tibetan Food',
 'May to September',
 'HIDDEN_GEM',
 'Free',
 true,
 'Hindi, Tibetan',
 'Spiti Valley'),

('Aizawl', 'Mizoram', 'India',
 'Capital city of Mizoram with scenic hills',
 'Durtlang Hills, Solomon Temple',
 'Bai, Bamboo Shoot Curry',
 'October to March',
 'MOUNTAINS',
 'Free',
 false,
 'Mizo, English',
 'Champhai'),

('Champhai', 'Mizoram', 'India',
 'Border town with Myanmar views and vineyards',
 'Rih Dil Lake, Murlen National Park',
 'Local Mizo Food',
 'October to March',
 'HIDDEN_GEM',
 'Free',
 true,
 'Mizo',
 'Aizawl'),

('Chopta', 'Uttarakhand', 'India',
 'Mini Switzerland of India with trekking routes',
 'Tungnath Temple, Chandrashila Trek',
 'Simple Garhwali Food',
 'March to June, September to November',
 'ADVENTURE',
 'Free',
 true,
 'Hindi',
 'Rishikesh, Rudraprayag'),
 ('Alibaug', 'Maharashtra', 'India',
 'Coastal getaway near Mumbai with beaches and forts',
 'Alibaug Beach, Kolaba Fort, Nagaon Beach',
 'Seafood, Kokam Drink',
 'November to March',
 'BEACHES',
 'Free',
 true,
 'Marathi, Hindi',
 'Mumbai, Mandwa'),

('Daman', 'Daman and Diu', 'India',
 'Portuguese coastal town with calm beaches',
 'Jampore Beach, Devka Beach',
 'Seafood, Gujarati Snacks',
 'October to March',
 'BEACHES',
 'Free',
 true,
 'Gujarati, Hindi',
 'Surat'),

('Diu', 'Daman and Diu', 'India',
 'Island with beaches, forts and nightlife',
 'Nagoa Beach, Diu Fort, Naida Caves',
 'Seafood',
 'October to March',
 'BEACHES',
 'Free',
 true,
 'Gujarati',
 'Somnath'),

('Gokarna', 'Karnataka', 'India',
 'Peaceful beach destination and spiritual town',
 'Om Beach, Kudle Beach, Paradise Beach',
 'Seafood, South Indian Food',
 'October to March',
 'BEACHES',
 'Free',
 true,
 'Kannada, English',
 'Goa, Udupi'),

('Varkala', 'Kerala', 'India',
 'Cliff beach with stunning sunset views',
 'Varkala Cliff, Papanasam Beach',
 'Seafood, Kerala Parotta',
 'October to March',
 'BEACHES',
 'Free',
 true,
 'Malayalam',
 'Kovalam, Trivandrum'),

('Kovalam', 'Kerala', 'India',
 'Popular beach destination near Trivandrum',
 'Lighthouse Beach, Hawa Beach',
 'Seafood, Appam',
 'September to March',
 'BEACHES',
 'Free',
 false,
 'Malayalam',
 'Trivandrum'),

('Munnar', 'Kerala', 'India',
 'Tea gardens and misty hill station',
 'Tea Gardens, Eravikulam Park',
 'Kerala Tea, Appam',
 'September to March',
 'MOUNTAINS',
 'Free',
 true,
 'Malayalam',
 'Thekkady, Kochi'),

('Ooty', 'Tamil Nadu', 'India',
 'Queen of hill stations with lakes and gardens',
 'Ooty Lake, Botanical Garden',
 'Chocolate, South Indian Food',
 'March to June',
 'MOUNTAINS',
 'Free',
 false,
 'Tamil',
 'Coonoor, Coimbatore'),

('Kodaikanal', 'Tamil Nadu', 'India',
 'Misty hill station with lakes and cliffs',
 'Kodaikanal Lake, Coaker’s Walk',
 'Home-made Chocolates',
 'March to June',
 'MOUNTAINS',
 'Free',
 true,
 'Tamil',
 'Madurai'),

('Coorg', 'Karnataka', 'India',
 'Coffee plantations and green hills',
 'Abbey Falls, Raja’s Seat',
 'Coffee, Pandi Curry',
 'October to March',
 'MOUNTAINS',
 'Free',
 true,
 'Kannada',
 'Mysore, Wayanad'),

('Lonavala', 'Maharashtra', 'India',
 'Monsoon hill station near Mumbai and Pune',
 'Tiger Point, Bhushi Dam',
 'Chikki, Vada Pav',
 'June to September',
 'MOUNTAINS',
 'Free',
 true,
 'Marathi',
 'Pune, Mumbai'),

('Mahabaleshwar', 'Maharashtra', 'India',
 'Strawberry hills and viewpoints',
 'Arthur’s Seat, Venna Lake',
 'Strawberries',
 'October to June',
 'MOUNTAINS',
 'Free',
 true,
 'Marathi',
 'Pune'),

('Dharamshala', 'Himachal Pradesh', 'India',
 'Tibetan culture and Himalayan views',
 'McLeod Ganj, Triund Trek',
 'Thukpa, Momos',
 'March to June',
 'MOUNTAINS',
 'Free',
 true,
 'Hindi, Tibetan',
 'McLeod Ganj'),

('Kasol', 'Himachal Pradesh', 'India',
 'Mini Israel of India in Parvati Valley',
 'Parvati River, Kheerganga Trek',
 'Israeli Food, Momos',
 'March to June',
 'ADVENTURE',
 'Free',
 true,
 'Hindi, English',
 'Manikaran'),

('Manali', 'Himachal Pradesh', 'India',
 'Adventure and snow destination',
 'Solang Valley, Rohtang Pass',
 'Thukpa, Trout Fish',
 'October to February',
 'ADVENTURE',
 'Free',
 false,
 'Hindi, English',
 'Kasol, Leh'),

('Goa', 'Goa', 'India',
 'Party capital with beaches and nightlife',
 'Baga Beach, Calangute Beach',
 'Seafood, Bebinca',
 'November to February',
 'BEACHES',
 'Free / varies',
 false,
 'Konkani',
 'Panaji'),

('Andaman Islands', 'Andaman and Nicobar', 'India',
 'Crystal clear waters and tropical islands',
 'Radhanagar Beach, Havelock Island',
 'Seafood',
 'October to May',
 'BEACHES',
 'Varies',
 false,
 'Hindi, English',
 'Port Blair'),

('Lakshadweep', 'Lakshadweep', 'India',
 'Remote coral islands with untouched beauty',
 'Agatti Island, Bangaram Island',
 'Seafood, Coconut Food',
 'October to March',
 'HIDDEN_GEM',
 'Permit Required',
 true,
 'Malayalam',
 'Arabian Sea Islands'),

('Kolkata', 'West Bengal', 'India',
 'City of joy with colonial history and artistic culture',
 'Victoria Memorial, Howrah Bridge, Dakshineswar Temple',
 'Rosogolla, Kathi Roll',
 'October to February',
 'HERITAGE',
 'Free / varies by attraction',
 false,
 'Bengali, Hindi, English',
 'Belur Math, Eco Park'),

('Chennai', 'Tamil Nadu', 'India',
 'Cultural capital of South India with temples and beaches',
 'Marina Beach, Kapaleeshwarar Temple, Fort St. George',
 'Idli, Dosa, Filter Coffee',
 'November to February',
 'BEACHES',
 'Free / varies by attraction',
 false,
 'Tamil, English',
 'Mahabalipuram, Santhome Basilica'),

('Bengaluru', 'Karnataka', 'India',
 'IT hub and garden city with pleasant climate',
 'Lalbagh Botanical Garden, Bangalore Palace, Cubbon Park',
 'Dosa, Bisi Bele Bath',
 'October to February',
 'PARTY',
 'Free / varies by attraction',
 false,
 'Kannada, English, Hindi',
 'Nandi Hills, Wonderla'),

('Jaipur', 'Rajasthan', 'India',
 'Pink City known for royal palaces and vibrant Rajasthani culture',
 'Hawa Mahal, Amber Fort, City Palace',
 'Dal Baati Churma, Ghewar',
 'October to March',
 'HERITAGE',
 'Free / varies by monument',
 false,
 'Hindi, Rajasthani',
 'Nahargarh Fort, Jal Mahal'),

('Hyderabad', 'Telangana', 'India',
 'Historic city blending Nizam heritage with modern tech culture',
 'Charminar, Golconda Fort, Hussain Sagar',
 'Hyderabadi Biryani, Haleem',
 'October to February',
 'HERITAGE',
 'Free / varies by attraction',
 false,
 'Telugu, Urdu, Hindi, English',
 'Ramoji Film City, Salar Jung Museum'),

('Pune', 'Maharashtra', 'India',
 'Educational and cultural city with youthful energy',
 'Shaniwar Wada, Aga Khan Palace, Sinhagad Fort',
 'Misal Pav, Bhakarwadi',
 'October to February',
 'ADVENTURE',
 'Free / varies by attraction',
 false,
 'Marathi, Hindi, English',
 'Lavasa, Mulshi Dam'),

('Ahmedabad', 'Gujarat', 'India',
 'Heritage and business city with rich Gujarati traditions',
 'Sabarmati Ashram, Kankaria Lake, Adalaj Stepwell',
 'Dhokla, Thepla, Fafda Jalebi',
 'November to February',
 'HERITAGE',
 'Free / varies by attraction',
 false,
 'Gujarati, Hindi',
 'Statue of Unity, Akshardham'),

('Kochi', 'Kerala', 'India',
 'Coastal port city with colonial history and backwater charm',
 'Fort Kochi, Chinese Fishing Nets, Mattancherry Palace',
 'Appam, Kerala Fish Curry',
 'October to March',
 'BEACHES',
 'Free / varies by attraction',
 true,
 'Malayalam, English',
 'Alleppey, Cherai Beach'),

('Chandigarh', 'Chandigarh', 'India',
 'Planned city with modern architecture and greenery',
 'Rock Garden, Sukhna Lake, Rose Garden',
 'Chole Bhature, Lassi',
 'October to March',
 'MOUNTAINS',
 'Free',
 false,
 'Hindi, English, Punjabi',
 'Morni Hills, Pinjore Gardens'),
('Surat', 'Gujarat', 'India',
 'Fast-growing city famous for street food',
 'Gordon Circle, Dutch Garden',
 'Locho, Surti Undhiyu, Ghari',
 'November to February',
 'FOOD_STREET',
 'Free',
 false,
 'Gujarati',
 'Daman'),

('Nagpur', 'Maharashtra', 'India',
 'Orange city with vibrant street food culture',
 'Sitabuldi, Futala Lake',
 'Samosa, Tarri Poha',
 'October to February',
 'FOOD_STREET',
 'Free',
 false,
 'Hindi, Marathi',
 'Pench'),

('Patna', 'Bihar', 'India',
 'Traditional Bihari street food hub',
 'Patna Market, Gandhi Maidan',
 'Litti Chokha, Sattu Paratha',
 'October to March',
 'FOOD_STREET',
 'Free',
 false,
 'Hindi, Bhojpuri',
 'Nalanda'),

('Kanpur', 'Uttar Pradesh', 'India',
 'Industrial city with spicy street food',
 'Phool Bagh, Z Square Mall',
 'Thaggu Ke Laddu, Chaat',
 'October to March',
 'FOOD_STREET',
 'Free',
 false,
 'Hindi',
 'Lucknow'),

('Bhopal', 'Madhya Pradesh', 'India',
 'City of lakes with rich street food',
 'New Market, Bhojtal',
 'Poha Jalebi, Kebabs',
 'October to March',
 'FOOD_STREET',
 'Free',
 false,
 'Hindi',
 'Sanchi'),

('Surendranagar', 'Gujarat', 'India',
 'Small city with Gujarati snacks culture',
 'Main Bazaar',
 'Fafda, Jalebi',
 'November to February',
 'FOOD_STREET',
 'Free',
 false,
 'Gujarati',
 'Ahmedabad'),

('Jamshedpur', 'Jharkhand', 'India',
 'Steel city with diverse food stalls',
 'Sakchi Market',
 'Chaat, Litti',
 'October to February',
 'FOOD_STREET',
 'Free',
 false,
 'Hindi',
 'Ranchi'),

('Coimbatore', 'Tamil Nadu', 'India',
 'South Indian food paradise',
 'RS Puram, Town Hall',
 'Idli, Dosa, Filter Coffee',
 'October to March',
 'FOOD_STREET',
 'Free',
 false,
 'Tamil',
 'Ooty'),
 ('Chennai', 'Tamil Nadu', 'India',
 'Nightlife mixed with beaches',
 'ECR Road, T Nagar',
 'South Indian + Drinks',
 'November to February',
 'PARTY',
 'Free',
 false,
 'Tamil',
 'Mahabalipuram'),

('Hyderabad', 'Telangana', 'India',
 'Modern nightlife with pubs',
 'Banjara Hills, Jubilee Hills',
 'Biryani, Kebabs',
 'October to February',
 'PARTY',
 'Free',
 false,
 'Telugu',
 'Warangal'),

('Ahmedabad', 'Gujarat', 'India',
 'Growing nightlife culture',
 'SG Highway, Prahlad Nagar',
 'Gujarati Snacks',
 'November to February',
 'PARTY',
 'Free',
 false,
 'Gujarati',
 'Surat'),

('Lucknow', 'Uttar Pradesh', 'India',
 'Cafes and lounges growing fast',
 'Hazratganj, Gomti Nagar',
 'Kebabs, Biryani',
 'October to March',
 'PARTY',
 'Free',
 false,
 'Hindi',
 'Kanpur'),

('Jaipur', 'Rajasthan', 'India',
 'Royal nightlife experience',
 'Malviya Nagar, C Scheme',
 'Dal Baati',
 'October to March',
 'PARTY',
 'Free',
 false,
 'Hindi',
 'Udaipur'),

('Indore', 'Madhya Pradesh', 'India',
 'Youth party hub',
 'Vijay Nagar',
 'Poha, Snacks',
 'October to March',
 'PARTY',
 'Free',
 false,
 'Hindi',
 'Bhopal'),

('Pune', 'Maharashtra', 'India',
 'College nightlife city',
 'Koregaon Park',
 'Maharashtrian Food',
 'October to February',
 'PARTY',
 'Free',
 false,
 'Marathi',
 'Mumbai'),

('Bangalore', 'Karnataka', 'India',
 'India’s pub capital',
 'Indiranagar, MG Road',
 'Craft Beer, Dosa',
 'October to February',
 'PARTY',
 'Free',
 false,
 'Kannada',
 'Mysore'),
 ('Ayodhya', 'Uttar Pradesh', 'India',
 'Birthplace of Lord Ram',
 'Ram Mandir, Saryu River',
 'Satvik Bhojan',
 'October to March',
 'RELIGIOUS',
 'Free',
 false,
 'Hindi',
 'Varanasi'),

('Ujjain', 'Madhya Pradesh', 'India',
 'One of 12 Jyotirlingas',
 'Mahakaleshwar Temple',
 'Poha, Kachori',
 'October to March',
 'RELIGIOUS',
 'Free',
 false,
 'Hindi',
 'Indore'),

('Dwarka', 'Gujarat', 'India',
 'Krishna’s ancient kingdom',
 'Dwarkadhish Temple',
 'Gujarati Thali',
 'October to March',
 'RELIGIOUS',
 'Free',
 false,
 'Gujarati',
 'Somnath'),

('Somnath', 'Gujarat', 'India',
 'Famous Shiva temple on coast',
 'Somnath Temple',
 'Seafood, Gujarati Food',
 'October to March',
 'RELIGIOUS',
 'Free',
 false,
 'Gujarati',
 'Dwarka'),

('Bodh Gaya', 'Bihar', 'India',
 'Buddha enlightenment place',
 'Mahabodhi Temple',
 'Vegetarian Food',
 'October to March',
 'RELIGIOUS',
 'Free',
 false,
 'Hindi, English',
 'Patna'),

('Shirdi', 'Maharashtra', 'India',
 'Sai Baba spiritual town',
 'Shirdi Temple',
 'Prasad Food',
 'Year Round',
 'RELIGIOUS',
 'Free',
 false,
 'Marathi',
 'Nashik'),

('Pushkar', 'Rajasthan', 'India',
 'Holy lake and Brahma temple',
 'Pushkar Lake',
 'Malpua',
 'October to March',
 'RELIGIOUS',
 'Free',
 false,
 'Hindi',
 'Ajmer'),

('Gangotri', 'Uttarakhand', 'India',
 'Origin of River Ganga',
 'Gangotri Temple',
 'Simple Food',
 'May to October',
 'RELIGIOUS',
 'Free',
 false,
 'Hindi',
 'Uttarkashi'),
 
('Varanasi', 'Uttar Pradesh', 'India',
 'Spiritual city on the banks of the Ganga with ancient traditions',
 'Kashi Vishwanath Temple, Dashashwamedh Ghat, Assi Ghat',
 'Kachori Sabzi, Banarasi Paan',
 'October to March',
 'RELIGIOUS',
 'Free / varies by attraction',
 false,
 'Hindi',
 'Sarnath, Ramnagar Fort');