INSERT INTO city (
    name, state, country, culture, tourist_spots, food,
    best_time_to_visit, category, entry_fee, is_hidden_gem, language, nearby_attractions
) VALUES
('Delhi', 'Delhi', 'India',
 'Capital city with rich Mughal and modern heritage',
 'India Gate, Red Fort, Qutub Minar',
 'Chole Bhature, Butter Chicken',
 'October to March',
 'HERITAGE',
 'Free / varies by monument',
 false,
 'Hindi, English',
 'Humayun''s Tomb, Lotus Temple'),

('Mumbai', 'Maharashtra', 'India',
 'Financial capital with Bollywood and coastal charm',
 'Gateway of India, Marine Drive, Elephanta Caves',
 'Vada Pav, Pav Bhaji',
 'November to February',
 'PARTY',
 'Free / varies by attraction',
 false,
 'Marathi, Hindi, English',
 'Juhu Beach, Siddhivinayak Temple'),

('Kolkata', 'West Bengal', 'India',
 'City of joy with colonial history and artistic culture',
 'Victoria Memorial, Howrah Bridge, Dakshineswar Temple',
 'Rosogolla, Kathi Roll',
 'October to February',
 'HERITAGE',
 'Free / varies by attraction',
 false,
 'Bengali, Hindi, English',
 'Belur Math, Eco Park'),

('Chennai', 'Tamil Nadu', 'India',
 'Cultural capital of South India with temples and beaches',
 'Marina Beach, Kapaleeshwarar Temple, Fort St. George',
 'Idli, Dosa, Filter Coffee',
 'November to February',
 'BEACHES',
 'Free / varies by attraction',
 false,
 'Tamil, English',
 'Mahabalipuram, Santhome Basilica'),

('Bengaluru', 'Karnataka', 'India',
 'IT hub and garden city with pleasant climate',
 'Lalbagh Botanical Garden, Bangalore Palace, Cubbon Park',
 'Dosa, Bisi Bele Bath',
 'October to February',
 'PARTY',
 'Free / varies by attraction',
 false,
 'Kannada, English, Hindi',
 'Nandi Hills, Wonderla'),

('Jaipur', 'Rajasthan', 'India',
 'Pink City known for royal palaces and vibrant Rajasthani culture',
 'Hawa Mahal, Amber Fort, City Palace',
 'Dal Baati Churma, Ghewar',
 'October to March',
 'HERITAGE',
 'Free / varies by monument',
 false,
 'Hindi, Rajasthani',
 'Nahargarh Fort, Jal Mahal'),

('Hyderabad', 'Telangana', 'India',
 'Historic city blending Nizam heritage with modern tech culture',
 'Charminar, Golconda Fort, Hussain Sagar',
 'Hyderabadi Biryani, Haleem',
 'October to February',
 'HERITAGE',
 'Free / varies by attraction',
 false,
 'Telugu, Urdu, Hindi, English',
 'Ramoji Film City, Salar Jung Museum'),

('Pune', 'Maharashtra', 'India',
 'Educational and cultural city with youthful energy',
 'Shaniwar Wada, Aga Khan Palace, Sinhagad Fort',
 'Misal Pav, Bhakarwadi',
 'October to February',
 'ADVENTURE',
 'Free / varies by attraction',
 false,
 'Marathi, Hindi, English',
 'Lavasa, Mulshi Dam'),

('Ahmedabad', 'Gujarat', 'India',
 'Heritage and business city with rich Gujarati traditions',
 'Sabarmati Ashram, Kankaria Lake, Adalaj Stepwell',
 'Dhokla, Thepla, Fafda Jalebi',
 'November to February',
 'HERITAGE',
 'Free / varies by attraction',
 false,
 'Gujarati, Hindi',
 'Statue of Unity, Akshardham'),

('Kochi', 'Kerala', 'India',
 'Coastal port city with colonial history and backwater charm',
 'Fort Kochi, Chinese Fishing Nets, Mattancherry Palace',
 'Appam, Kerala Fish Curry',
 'October to March',
 'BEACHES',
 'Free / varies by attraction',
 true,
 'Malayalam, English',
 'Alleppey, Cherai Beach'),

('Chandigarh', 'Chandigarh', 'India',
 'Planned city with modern architecture and greenery',
 'Rock Garden, Sukhna Lake, Rose Garden',
 'Chole Bhature, Lassi',
 'October to March',
 'MOUNTAINS',
 'Free',
 false,
 'Hindi, English, Punjabi',
 'Morni Hills, Pinjore Gardens'),

('Varanasi', 'Uttar Pradesh', 'India',
 'Spiritual city on the banks of the Ganga with ancient traditions',
 'Kashi Vishwanath Temple, Dashashwamedh Ghat, Assi Ghat',
 'Kachori Sabzi, Banarasi Paan',
 'October to March',
 'RELIGIOUS',
 'Free / varies by attraction',
 false,
 'Hindi',
 'Sarnath, Ramnagar Fort');